imports:
- https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/Wrk2Client/wrk2.yml
variables:
  headers:
    none: ''
    json: "--header Accept:application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7 --header Connection:keep-alive"
    plaintext: "--header Accept:text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7 --header Connection:keep-alive"
    connectionclose: "--header Connection:close"
  presetHeaders: none
  path: "/"
jobs:
  weatherapp-route-to-code:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: "weatherapp-route-to-code"
      dockerContextDirectory: "dotnet/weatherapp-route-to-code/"
      dockerFile: "dotnet/weatherapp-route-to-code/Dockerfile"
    readyStateText: Application started.
  weatherapp-controllers:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-controllers
      dockerContextDirectory: dotnet/weatherapp-controllers/
      dockerFile: dotnet/weatherapp-controllers/Dockerfile
    readyStateText: Application started.
  weatherapp-grpc:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-grpc
      dockerContextDirectory: dotnet/weatherapp-grpc/
      dockerFile: dotnet/weatherapp-grpc/Dockerfile
    readyStateText: Application started.
  weatherapp-springboot:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-springboot
      dockerContextDirectory: java/weatherapp-springboot/
      dockerFile: java/weatherapp-springboot/Dockerfile
    readyStateText: Started WeatherappApplication
  weatherapp-springbootwebflux:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-springbootwebflux
      dockerContextDirectory: java/weatherapp-springbootwebflux/
      dockerFile: java/weatherapp-springbootwebflux/Dockerfile
    readyStateText: Started WeatherappApplication
  weatherapp-quarkus-graal:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-quarkus
      dockerContextDirectory: java/weatherapp-quarkus/
      dockerFile: java/weatherapp-quarkus/Dockerfile.graal
    readyStateText: "Listening on: http://0.0.0.0"
  weatherapp-quarkus-jvm:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-quarkus
      dockerContextDirectory: java/weatherapp-quarkus/
      dockerFile: java/weatherapp-quarkus/Dockerfile.jvm
    readyStateText: "Listening on: http://0.0.0.0:5000"
  weatherapp-go:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-go
      dockerContextDirectory: go/weatherapp-go/
      dockerFile: go/weatherapp-go/Dockerfile
    readyStateText: app listening on port 5000!
  weatherapp-gofasthttp:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-gofasthttp
      dockerContextDirectory: go/weatherapp-gofasthttp/
      dockerFile: go/weatherapp-gofasthttp/Dockerfile
    readyStateText: app listening on port 5000!
  weatherapp-express:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-express
      dockerContextDirectory: node/weatherapp-express/
      dockerFile: node/weatherapp-express/Dockerfile
    readyStateText: app listening on port 5000!
  weatherapp-expressclustered:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-expressclustered
      dockerContextDirectory: node/weatherapp-expressclustered/
      dockerFile: node/weatherapp-expressclustered/Dockerfile
    readyStateText: app listening on port 5000!
  weatherapp-aiohttp:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-aiohttp
      dockerContextDirectory: python/weatherapp-aiohttp/
      dockerFile: python/weatherapp-aiohttp/Dockerfile
    readyStateText: 'Listening at:'
  weatherapp-flask:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: weatherapp-flask
      dockerContextDirectory: python/weatherapp-flask/
      dockerFile: python/weatherapp-flask/Dockerfile
    readyStateText: 'Listening at:'
  forecastapp-gofasthttp:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: forecastapp-gofasthttp
      dockerContextDirectory: go/forecastapp-gofasthttp/
      dockerFile: go/forecastapp-gofasthttp/Dockerfile
    readyStateText: app listening on port 8080!
  forecastapp-gogrpc:
    source:
      repository: https://github.com/rynowak/benchmarks-playground.git
      branchOrCommit: master
      dockerImageName: forecastapp-gogrpc
      dockerContextDirectory: go/forecastapp-gogrpc/
      dockerFile: go/forecastapp-gogrpc/Dockerfile
    readyStateText: app listening on port 8080!
scenarios:
  weatherapp-route-to-code:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-route-to-code
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-controllers:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-controllers
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-go:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-go
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-gofasthttp:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-gofasthttp
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-springboot:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-springboot
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-springbootwebflux:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-springbootwebflux
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-quarkus:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-quarkus
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-express:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-express
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
  weatherapp-flask:
    forecast:
      job: forecastapp-gofasthttp
    weather:
      job: weatherapp-flask
    warmup:
      job: wrk2
      variables:
        path: /
        duration: 20
        rate: 50
      options:
        discardResults: true
    load:
      job: wrk2
      variables:
        path: /
        duration: 20
